import { createRouter, publicQuery } from "./middleware";
import { connectMongo } from "../mongo/connection";
import { Room } from "../mongo/models";

const demoRooms = [
  {
    title: "Premium Podcast Studio",
    description: "Professional podcast studio with 4-host setup, soundproofing, Rode PodMic microphones, Rodecaster Pro mixer, and acoustic treatment. Perfect for podcasters, interview shows, and voice-over work.",
    category: "podcast" as const,
    city: "Patna",
    address: "Boring Road, Patna, Bihar 800001",
    pricePerHour: 499,
    weekendPrice: 599,
    maxGuests: 4,
    rating: 4.8,
    reviewCount: 24,
    status: "active" as const,
    featuredImage: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800",
      "https://images.unsplash.com/photo-1589903308904-1010c2294adc?w=800",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800",
    ]),
    amenities: JSON.stringify(["Soundproof Room", "Air Conditioning", "High-Speed WiFi", "Waiting Area", "Free Parking", "Tea/Coffee"]),
    rules: JSON.stringify(["No smoking inside the studio", "Food and drinks not allowed near equipment", "Maximum 4 people allowed", "Advance booking required", "Clean up after your session"]),
    equipment: JSON.stringify(["Rode PodMic x4", "Rodecaster Pro", "Closed-back Headphones x4", "Acoustic Foam Panels", "Pop Filters", "Mic Stands x4"]),
    lightingSetup: JSON.stringify(["Ring Light", "Soft Box", "RGB Accent Lights"]),
    threeSixtyImage: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=1200",
  },
  {
    title: "Gaming Arena Pro",
    description: "High-end gaming setup with 10 battle stations, 240Hz monitors, RTX 4080 GPUs, mechanical keyboards, and tournament-grade headsets. Ideal for esports tournaments, streaming, and gaming content creation.",
    category: "gaming" as const,
    city: "Patna",
    address: "Kankarbagh, Patna, Bihar 800020",
    pricePerHour: 399,
    weekendPrice: 499,
    maxGuests: 10,
    rating: 4.6,
    reviewCount: 18,
    status: "active" as const,
    featuredImage: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800",
      "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800",
      "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800",
    ]),
    amenities: JSON.stringify(["High-Speed WiFi", "Air Conditioning", "Refreshment Bar", "Streaming Setup", "Tournament Area", "Free Parking"]),
    rules: JSON.stringify(["No food at gaming stations", "Headphones must be returned after use", "Report any equipment issues immediately", "Maximum 10 players", "External devices must be scanned"]),
    equipment: JSON.stringify(["RTX 4080 GPUs", "240Hz Monitors", "Mechanical Keyboards", "Gaming Mice", "Tournament Headsets", "Gaming Chairs x10"]),
    lightingSetup: JSON.stringify(["RGB Strip Lights", "LED Ceiling Panels", "Desk RGB"]),
    threeSixtyImage: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200",
  },
  {
    title: "Reel Studio Deluxe",
    description: "Instagram and YouTube reel creation studio with ring lights, green screen, multiple backdrops, and professional camera setup. Create viral content with our premium equipment.",
    category: "reel_studio" as const,
    city: "Mumbai",
    address: "Andheri West, Mumbai, Maharashtra 400053",
    pricePerHour: 349,
    weekendPrice: 449,
    maxGuests: 3,
    rating: 4.7,
    reviewCount: 32,
    status: "active" as const,
    featuredImage: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800",
      "https://images.unsplash.com/photo-1471341971476-ae15ff5dd4ea?w=800",
      "https://images.unsplash.com/photo-1492619375914-88005aa9e8fb?w=800",
    ]),
    amenities: JSON.stringify(["Green Screen", "Changing Room", "Makeup Station", "High-Speed WiFi", "Props Collection", "Coffee Bar"]),
    rules: JSON.stringify(["Handle camera equipment with care", "Clean backdrops after use", "No outdoor shoes on set", "Props must be returned", "Booking minimum 1 hour"]),
    equipment: JSON.stringify(["Sony A7III", "Ring Light 18\"", "Green Screen", "Soft Box Set", "Tripod", "Wireless Mic"]),
    lightingSetup: JSON.stringify(["Ring Light", "Soft Box x2", "RGB Panel", "Spotlight"]),
    threeSixtyImage: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=1200",
  },
  {
    title: "RGB Content Room",
    description: "Immersive RGB-lit content creation room with customizable lighting, neon accents, and mood-based setups. Perfect for tech reviews, unboxing videos, and aesthetic content.",
    category: "rgb_room" as const,
    city: "Delhi",
    address: "Connaught Place, New Delhi 110001",
    pricePerHour: 299,
    weekendPrice: 399,
    maxGuests: 2,
    rating: 4.5,
    reviewCount: 15,
    status: "active" as const,
    featuredImage: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800",
      "https://images.unsplash.com/photo-1615663245857-acda847f8423?w=800",
      "https://images.unsplash.com/photo-1515630278258-407f66498911?w=800",
    ]),
    amenities: JSON.stringify(["RGB Lighting Control", "High-Speed WiFi", "Air Conditioning", "Product Display Shelf", "USB Charging Ports"]),
    rules: JSON.stringify(["RGB presets should be restored after use", "No liquids near electronics", "Maximum 2 creators", "Handle remote controls carefully"]),
    equipment: JSON.stringify(["Sony ZV-1", "RGB LED Panels", "Neon Light Tubes", "Smart Bulbs", "Wireless Charger", "USB Hub"]),
    lightingSetup: JSON.stringify(["RGB Panels", "Neon Tubes x4", "Smart Bulbs", "LED Strip", "Mood Lighting"]),
    threeSixtyImage: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200",
  },
  {
    title: "Music Recording Studio",
    description: "Acoustically treated recording studio with Yamaha HS monitors, Focusrite interface, condenser mic, and MIDI keyboard. Record vocals, podcasts, and music with studio-quality sound.",
    category: "music" as const,
    city: "Bangalore",
    address: "Koramangala, Bangalore, Karnataka 560034",
    pricePerHour: 599,
    weekendPrice: 699,
    maxGuests: 3,
    rating: 4.9,
    reviewCount: 28,
    status: "active" as const,
    featuredImage: "https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=800",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=800",
      "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800",
      "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800",
    ]),
    amenities: JSON.stringify(["Acoustic Treatment", "Air Conditioning", "High-Speed WiFi", "Relaxation Area", "Instrument Storage"]),
    rules: JSON.stringify(["No loud instruments without prior notice", "Handle microphones with care", "No food in recording area", "Sessions may be recorded for quality"]),
    equipment: JSON.stringify(["Focusrite Scarlett 2i2", "Audio-Technica AT2020", "Yamaha HS8 Monitors", "MIDI Keyboard 61-key", "Audio Interface", "Studio Headphones"]),
    lightingSetup: JSON.stringify(["Warm Ambient", "LED Dimmable"]),
    threeSixtyImage: "https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=1200",
  },
  {
    title: "Dance Studio",
    description: "Spacious dance studio with full-length mirrors, wooden flooring, professional sound system, and video recording setup. Perfect for choreography practice, dance covers, and fitness content.",
    category: "dance" as const,
    city: "Mumbai",
    address: "Bandra West, Mumbai, Maharashtra 400050",
    pricePerHour: 449,
    weekendPrice: 549,
    maxGuests: 8,
    rating: 4.4,
    reviewCount: 12,
    status: "active" as const,
    featuredImage: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800",
      "https://images.unsplash.com/photo-1524594152303-9fd13543fe6e?w=800",
    ]),
    amenities: JSON.stringify(["Full-length Mirrors", "Sound System", "Changing Room", "High-Speed WiFi", "Water Dispenser", "First Aid Kit"]),
    rules: JSON.stringify(["Wear clean dance shoes or barefoot only", "No food on dance floor", "Sound system instructions must be followed", "Maximum 8 dancers", "Clean floor after session"]),
    equipment: JSON.stringify(["Bluetooth Speaker System", "Phone/Camera Tripod", "Props Storage", "Yoga Mats", "Stretching Bars"]),
    lightingSetup: JSON.stringify(["Natural Light", "Overhead LED", "Spotlights"]),
    threeSixtyImage: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200",
  },
];

export const mongoSeedRouter = createRouter({
  run: publicQuery.mutation(async () => {
    await connectMongo();
    const count = await Room.countDocuments();
    if (count === 0) {
      await Room.insertMany(demoRooms.map((r) => ({ ...r, hostId: "000000000000000000000000" })));
      return { seeded: true, count: demoRooms.length };
    }
    return { seeded: false, count };
  }),
});
